name: Deploy Lambda

on:
  push:
    branches:
      - main  # Executa o deploy quando há push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checando Repo
      uses: actions/checkout@v3

    - name: Set up do Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: NPM Install
      run: npm install 

    - name: Verificar AWS CLI
      run: aws --version

    - name: Zip Lambda function
      run: zip -r lambda.zip index.js node_modules

    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Criar API Gateway
      run: |
        API_ID=$(aws apigatewayv2 create-api \
          --name "apiGatewayLambda" \
          --protocol-type HTTP \
          --description "API Gateway para Lambda de validação de usuário" \
          --query "ApiId" \
          --output text)
        echo "API_ID=$API_ID" >> $GITHUB_ENV

    - name: Criar Função Lambda
      run: |
        aws lambda create-function \
          --function-name getUserByCpf \
          --runtime nodejs20.x \
          --handler index.handler \
          --zip-file fileb://lambda.zip \
          --timeout 10 \
          --memory-size 128 \
          --role arn:aws:iam::300254322294:role/LabRole

    - name: Criar Integração Lambda no API Gateway
      run: |
        INTEGRATION_ID=$(aws apigatewayv2 create-integration \
          --api-id ${{ env.API_ID }} \
          --integration-type AWS_PROXY \
          --integration-uri arn:aws:lambda:us-east-1:443892199384:function:getUserByCpf \
          --payload-format-version 2.0 \
          --query "IntegrationId" \
          --output text)
        echo "INTEGRATION_ID=$INTEGRATION_ID" >> $GITHUB_ENV

    - name: Criar Rota GET /users/{cpf}
      run: |
        aws apigatewayv2 create-route \
          --api-id ${{ env.API_ID }} \
          --route-key "GET /users/{cpf}" \
          --target integrations/${{ env.INTEGRATION_ID }}

    - name: Criar Deploy da API
      run: |
        DEPLOYMENT_ID=$(aws apigatewayv2 create-deployment \
          --api-id ${{ env.API_ID }} \
          --query "DeploymentId" \
          --output text)
        echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
        aws apigatewayv2 create-stage \
          --api-id ${{ env.API_ID }} \
          --stage-name "dev" \
          --deployment-id $DEPLOYMENT_ID

    - name: Dar Permissão ao Lambda
      run: |
        aws lambda add-permission \
          --function-name getUserByCpf \
          --statement-id apigateway-access \
          --action lambda:InvokeFunction \
          --principal apigateway.amazonaws.com \
          --source-arn arn:aws:execute-api:us-east-1:443892199384:${{ env.API_ID }}/*/GET/users/*
